// Define the Scratch directory
def scratch_dir = System.getenv("USER_SCRATCH") ?: "/tmp"

params {
    config_profile_name = 'linux_local'
    config_profile_description = 'Generic Linux system configuration'
    config_profile_contact = 'Your Name (your_email@example.com)'
    config_profile_url = 'https://example.com'
}

env {
    TMPDIR = "$scratch_dir"
    SINGULARITY_TMPDIR = "$scratch_dir"
}


// Function to limit resources
def limitResources = { memory, cpus ->
    memory = Math.min(memory.toMega(), 1024 * 1024)
    cpus = Math.min(cpus, 60)                       
    return [memory: memory.GB, cpus: cpus]
}



process {
    // Maximum default resources for all processes
    memory = '1024.GB' // 1 TB
    cpus = 60
    time = 150.h

    // Use local executor for Linux
    executor = 'local'

    maxRetries = 3
   
}

// process specific configs
process {
    withName: '.*:ASE_QUANT_MATRIX' {
	time = '1000.h'
        cpus = Math.min(60, 80)
    }
}

process {
    withName: '.*:ISOSCELES' {
        time = '1000.h'
        cpus = Math.min(20, 30)
	memory = '256.GB'
    }
}

process {
    withName: '.*:.*FASTQC.*' {
        cpus = Math.min(25, 60)
    }
}

process {
    withName: '.*:.*BLAZE.*' {
        cpus = Math.min(45, 60)
        memory = '55.GB'
    }
}

process {
    withName: '.*:TAG_BARCODES' {
        memory = '70.GB'
    }
}

process {
    withName: '.*:SAMTOOLS_SORT' {
        cpus = Math.min(25, 60)
    }
}

process {
    withName: '.*:PIGZ' {
        cpus = Math.min(35, 60)
    }
}

process {
    withName: '.*:MINIMAP2_ALIGN' {
        cpus = Math.min(25, 60)
    }
}

process {
    withName: '.*:ISOQUANT' {
        cpus = Math.min(40, 60)
        memory = '125.GB'
        time = '100.h'
    }
}

